/**
 * Crimson Atlas Native Workspace — Tab 2 feeder-school directory data.
 * Content is preserved from the user's tab2prompt.docx and is not independently shortened.
 */

export type SchoolType = "International" | "Local";

export type FeederSchool = {
  name: string;
  type: SchoolType;
  curricula: string[];
  primaryTarget: string;
  students: number;
  highflyers: number;
  counsellors: string;
  counsellingEnvironment: string;
  guidanceStarts: string;
  academicRating: number;
  academicStrength: string;
  extracurricularRating: number;
  extracurricularEnvironment: string;
  teacherGuidanceRating: number;
  teacherGuidance: string;
};

export const ibResultsUrl = "https://www.hk-schools.com/post/hong-kong-ib-results-2026";

export const feederSchools: FeederSchool[] = [
  {
    name: "Canadian International School of Hong Kong (CDNIS)",
    type: "International",
    curricula: ["IB", "AP"],
    primaryTarget: "US / Canada",
    students: 32,
    highflyers: 12,
    counsellors: "4",
    counsellingEnvironment: "Highly structured",
    guidanceStarts: "Grade 9",
    academicRating: 4,
    academicStrength: "Strong international academic profile across IB and AP. AP-track students can build rigorous US-style course profiles; the school also supports strong economics and political-economy applicants.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong Model UN, debate, community service and cultural-exchange environment. Student activities are broad and service-oriented; the school supports meaningful participation beyond the classroom, including language outreach and high-level martial arts.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Strong Model UN, debate, service-learning and cultural-exchange options give teachers clear activities to recommend. Best for students who want service, global engagement or broad co-curricular exposure.",
  },
  {
    name: "Chinese International School (CIS)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "US / UK",
    students: 58,
    highflyers: 15,
    counsellors: "5",
    counsellingEnvironment: "Very strong, dedicated university counselling plus career exploration",
    guidanceStarts: "Year 10",
    academicRating: 4,
    academicStrength: "Highly selective, academically demanding bilingual international school. Particularly strong for students with humanities, language and intellectually driven profiles.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong arts, journalism, debate and bilingual/cross-cultural activities. The English–Mandarin environment creates genuine opportunities for bilingual journalism, cultural outreach and language-based projects; student initiatives can connect naturally to the school’s bilingual mission.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Teachers can point students toward strong arts, journalism, debate and bilingual/cross-cultural projects. Particularly useful for students whose interests connect with the school’s English-Mandarin environment.",
  },
  {
    name: "German Swiss International School (GSIS)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "UK / Germany",
    students: 35,
    highflyers: 10,
    counsellors: "3",
    counsellingEnvironment: "Strong, dedicated university and careers counselling",
    guidanceStarts: "Year 10",
    academicRating: 4,
    academicStrength: "Rigorous international academics with IB and a German-language stream. Small-school setting gives students relatively strong individual academic support; suitable for UK/Germany-focused students and some US applicants.",
    extracurricularRating: 3,
    extracurricularEnvironment: "Smaller school means fewer school-run clubs, but students who want to start an initiative generally can. Strong outdoor education, Duke of Edinburgh, community activities and competitive sport; the culture is more community-oriented than entrepreneurial.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. The small-school setting means teachers know students personally, which supports more tailored ECL suggestions. Strongest recommendations are likely around outdoor education, Duke of Edinburgh, community activities and sport.",
  },
  {
    name: "Harrow International School Hong Kong",
    type: "International",
    curricula: ["A-Level"],
    primaryTarget: "UK",
    students: 40,
    highflyers: 12,
    counsellors: "N/A",
    counsellingEnvironment: "Highly structured",
    guidanceStarts: "Year 12",
    academicRating: 4,
    academicStrength: "Rigorous British-style academic environment with strong A-Level preparation. Structured, exam-focused and particularly strong for traditional humanities and UK-oriented academic profiles.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Rich co-curricular programme built around the house system, leadership and competitive sports such as cricket, rowing and rugby. Students can start initiatives, but new clubs normally go through formal school channels, so the process is more structured and slower.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good but structured. Teachers can guide students into the house system, leadership and competitive sports, but new initiatives normally need to follow formal school channels.",
  },
  {
    name: "Hong Kong International School (HKIS)",
    type: "International",
    curricula: ["AP", "IB"],
    primaryTarget: "US",
    students: 61,
    highflyers: 16,
    counsellors: "8",
    counsellingEnvironment: "Highly integrated and personalised",
    guidanceStarts: "Grade 9",
    academicRating: 5,
    academicStrength: "Exceptionally strong US-track academic environment with rigorous AP options and an established international profile. Strong fit for highly ambitious US applicants; the school also supports IB study.",
    extracurricularRating: 5,
    extracurricularEnvironment: "One of the strongest environments for student initiative. Starting clubs is genuinely easy and founder culture is common; strong opportunities also exist in APAC sport, VEX Robotics, high-level music, entrepreneurship and research.",
    teacherGuidanceRating: 5,
    teacherGuidance: "Excellent. The school actively supports student entrepreneurship, research, robotics, sports, arts and club creation. Teachers have many established and student-led options to recommend based on a student’s interests.",
  },
  {
    name: "The ISF Academy",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "US / UK / China",
    students: 37,
    highflyers: 12,
    counsellors: "4",
    counsellingEnvironment: "Very structured University Guidance",
    guidanceStarts: "Grade 9",
    academicRating: 5,
    academicStrength: "Highly prestigious, academically rigorous bilingual school. Especially strong for high-achieving STEM students, Olympiad competitors and students who can demonstrate advanced work in both English and Mandarin.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong academic-competition culture, including Math/Science Olympiads, bilingual creative writing and debate. Student success is often built around research, competitions and structured achievement; less naturally founder/start-up driven than HKIS.",
    teacherGuidanceRating: 5,
    teacherGuidance: "Excellent for academic ECL. Teachers can guide students toward Math/Science Olympiads, research, bilingual writing and debate. Strongest for students seeking competition- or research-based activities rather than founder-style clubs.",
  },
  {
    name: "Sha Tin College (ESF)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "UK / US",
    students: 21,
    highflyers: 8,
    counsellors: "2",
    counsellingEnvironment: "Strong, dedicated guidance",
    guidanceStarts: "N/A",
    academicRating: 3,
    academicStrength: "Broad ESF academic environment with a wide range of student ambition. Solid international preparation, but students need to distinguish themselves individually within a large and diverse cohort.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong co-curricular tradition with Duke of Edinburgh, drama, sports and inter-school competitions. Starting a club is relatively straightforward within the ESF framework, giving students reasonable room to create initiatives.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate. Teachers can recommend established ESF activities such as Duke of Edinburgh, drama, sports and inter-school competitions. Support is broad, but the source suggests teacher experience is mixed, so quality may vary by teacher.",
  },
  {
    name: "Victoria Shanghai Academy (VSA)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "US / UK",
    students: 17,
    highflyers: 4,
    counsellors: "N/A",
    counsellingEnvironment: "Very structured University Counselling Office",
    guidanceStarts: "Year 9",
    academicRating: 4,
    academicStrength: "Strong bilingual IB academic environment with growing strength in arts and social sciences. Good fit for students whose academic profile benefits from genuine English–Mandarin study.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong bilingual arts, social entrepreneurship, community service and cross-cultural projects. There is meaningful room for student-initiated projects, and the bilingual environment can give activities a distinctive cultural or community angle.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Teachers can recommend bilingual arts, social entrepreneurship, community service and cross-cultural projects. The school also gives students meaningful room to develop their own initiatives.",
  },
  {
    name: "West Island School (ESF)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "UK / US",
    students: 6,
    highflyers: 2,
    counsellors: "3",
    counsellingEnvironment: "Strong, dedicated guidance",
    guidanceStarts: "Year 12",
    academicRating: 3,
    academicStrength: "Broad ESF academic environment serving students with varied levels of ambition. Strong individual students can build competitive profiles, but the school itself is not positioned at the most academically selective end.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong outdoor education, drama, music, student journalism and Duke of Edinburgh. Sports are competitive within ESF; the school provides a well-established co-curricular environment for sustained involvement.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate. Teachers can direct students toward outdoor education, drama, music, journalism, Duke of Edinburgh and ESF sport. The range is solid, but teacher support quality may vary.",
  },
  {
    name: "Po Leung Kuk Choi Kai Yau School (CKY)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "US / UK",
    students: 4,
    highflyers: 1,
    counsellors: "2",
    counsellingEnvironment: "Dedicated University Guidance Centre offering individual consultations",
    guidanceStarts: "N/A",
    academicRating: 4,
    academicStrength: "Distinctive bilingual academic environment combining Chinese independent-school traditions with IB. Particularly strong for arts, humanities and students with a clear Chinese cultural identity.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong arts, Chinese cultural performance, community service and humanities-oriented activities. The environment supports culturally distinctive projects, though technology/start-up activity is less central than at schools such as HKIS or CIS.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate. Teachers can recommend strong arts, Chinese cultural performance, community service and humanities activities. Best for students with cultural or creative interests; less strong for tech or entrepreneurship-focused ECL.",
  },
  {
    name: "King George V School (KGV — ESF)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "UK / US",
    students: 19,
    highflyers: 5,
    counsellors: "2",
    counsellingEnvironment: "Strong Careers & Higher Education Guidance team",
    guidanceStarts: "Year 12",
    academicRating: 4,
    academicStrength: "One of the academically stronger ESF schools, with a long-established international environment. Good platform for motivated, globally minded students targeting UK and US universities.",
    extracurricularRating: 5,
    extracurricularEnvironment: "One of the strongest extracurricular cultures in the ESF network. Student-run clubs are abundant, Model UN is competitive, drama and music are strong, and starting a new club is straightforward and actively supported.",
    teacherGuidanceRating: 5,
    teacherGuidance: "Excellent. Student-run clubs are abundant and starting a club is straightforward. Teachers can recommend strong Model UN, drama, music and student-led opportunities in a school culture that actively encourages initiative.",
  },
  {
    name: "Kellett School",
    type: "International",
    curricula: ["A-Level", "IGCSE"],
    primaryTarget: "UK",
    students: 12,
    highflyers: 3,
    counsellors: "N/A",
    counsellingEnvironment: "Strong, personalised University Guidance",
    guidanceStarts: "Year 12",
    academicRating: 4,
    academicStrength: "Strong British academic environment through IGCSE and A-Level. Structured and exam-oriented, with a clear fit for students targeting UK universities.",
    extracurricularRating: 3,
    extracurricularEnvironment: "Solid house-system activities with sport and drama well supported. Extracurricular provision is structured, but there is less emphasis on entrepreneurship, independent research or student-created initiatives than at the top international schools.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate. Teachers can guide students toward the house system, sport and drama, but the source shows fewer distinctive opportunities in entrepreneurship, research or student-created initiatives.",
  },
  {
    name: "South Island School (SIS — ESF)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "UK / US",
    students: 21,
    highflyers: 8,
    counsellors: "1",
    counsellingEnvironment: "Strong post-secondary and Higher Education support",
    guidanceStarts: "Year 11",
    academicRating: 3,
    academicStrength: "Broad ESF academic environment with varied student ambition. Individual motivated students can stand out, but the school is not among the most academically selective international schools.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Particularly strong creative and entrepreneurial environment for an ESF school. Design, technology, student start-ups, community projects and maker-style activities are visible, with facilities that support hands-on student initiatives.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Teachers can recommend design, technology, maker activities, student start-ups and community projects. Particularly useful for creative or entrepreneurial students who want hands-on ECL.",
  },
  {
    name: "Island School (ESF)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "UK / US",
    students: 20,
    highflyers: 6,
    counsellors: "N/A",
    counsellingEnvironment: "Dedicated Higher Education function supporting",
    guidanceStarts: "Year 12",
    academicRating: 3,
    academicStrength: "Established ESF academic environment with a broad and genuinely international student body. Students need to build individual distinction within a diverse cohort.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong service-learning and global-citizenship culture. Environmental sustainability, community outreach and international exchange are prominent, making the school especially supportive of social-impact and service-focused extracurricular profiles.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Teachers can guide students toward service-learning, sustainability, community outreach and international exchange. Strong fit for students who want social-impact or global-citizenship activities.",
  },
  {
    name: "Yew Chung International School (YCIS)",
    type: "International",
    curricula: ["IB"],
    primaryTarget: "US / UK",
    students: 7,
    highflyers: 4,
    counsellors: "4",
    counsellingEnvironment: "Highly structured University Guidance Office",
    guidanceStarts: "Year 12",
    academicRating: 4,
    academicStrength: "Strong bilingual IB academic environment, particularly in STEM. The dual-language English–Mandarin track provides a meaningful academic differentiator through secondary school.",
    extracurricularRating: 3,
    extracurricularEnvironment: "School-based extracurricular culture is more academically focused and less entrepreneurial. Service and cultural exchange are available, while highly ambitious students often build stronger research or competition activities outside school.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate. Teachers can recommend service and cultural-exchange activities, but the school is more academically focused than extracurricularly vibrant. Ambitious students may need external research or competitions for stronger ECL options.",
  },
  {
    name: "Singapore International School HK (SISHK)",
    type: "International",
    curricula: ["Singapore O/A-Level"],
    primaryTarget: "SG / UK / ANZ",
    students: 15,
    highflyers: 2,
    counsellors: "N/A",
    counsellingEnvironment: "Structured Education & Career Guidance",
    guidanceStarts: "N/A",
    academicRating: 3,
    academicStrength: "Solid, disciplined Singapore-style academic environment with a strong STEM tradition. Best aligned with students targeting Singapore, UK and Australian/New Zealand universities rather than a primarily US-track pathway.",
    extracurricularRating: 3,
    extracurricularEnvironment: "Co-curricular activities are structured through the school-controlled CCA system. Opportunities exist, but starting an independent club is harder than at more student-led IB or US-style schools because activities operate within a more regimented framework.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Structured. Teachers can guide students within the school-controlled CCA system, but independent club creation is harder. Best for students comfortable with established, curriculum-linked activities rather than self-created initiatives.",
  },
  {
    name: "St. Paul's Co-educational College (SPCC)",
    type: "Local",
    curricula: ["HKDSE"],
    primaryTarget: "HK / UK",
    students: 12,
    highflyers: 4,
    counsellors: "N/A",
    counsellingEnvironment: "Established Life Planning & Careers Guidance programme combining self-development, academic counselling and further-study guidance.",
    guidanceStarts: "N/A",
    academicRating: 5,
    academicStrength: "One of Hong Kong’s top Band 1 schools with a highly competitive HKDSE academic culture. Strong across both STEM and humanities and suitable for academically exceptional local-school students.",
    extracurricularRating: 3,
    extracurricularEnvironment: "Strong music, orchestra, choir, drama, community service and competitive student government. Activities are school-directed; starting a new club or independent initiative generally requires more institutional approval than at international schools.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate and school-directed. Teachers can recommend strong music, drama, community service and student government opportunities, but new clubs or independent initiatives require more institutional approval.",
  },
  {
    name: "Diocesan Girls' School (DGS)",
    type: "Local",
    curricula: ["HKDSE"],
    primaryTarget: "HK / UK",
    students: 15,
    highflyers: 3,
    counsellors: "1",
    counsellingEnvironment: "Very strong Careers & Life Planning provision",
    guidanceStarts: "Not stated",
    academicRating: 5,
    academicStrength: "One of Hong Kong’s most academically competitive girls’ schools. Strong HKDSE performance with notable strength across humanities, languages and STEM.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Exceptionally active for a local school, with strong debating, international competitions, music, community service and student leadership. The environment explicitly supports girls’ leadership, although activities remain more organised and school-structured than at international schools.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Teachers can guide students toward debating, music, community service and leadership in a very active local-school co-curricular environment. Opportunities are strong, though more organised than at international schools.",
  },
  {
    name: "Diocesan Boys' School (DBS)",
    type: "Local",
    curricula: ["HKDSE"],
    primaryTarget: "HK / UK",
    students: 8,
    highflyers: 3,
    counsellors: "N/A",
    counsellingEnvironment: "Very structured",
    guidanceStarts: "Grade 12",
    academicRating: 5,
    academicStrength: "Elite Band 1 academic environment with particularly strong Mathematics, Science and Olympiad traditions. Well suited to high-achieving STEM students and competition-oriented profiles.",
    extracurricularRating: 4,
    extracurricularEnvironment: "Strong debate, Model UN, orchestra and competitive sports, especially rowing, rugby and basketball. Student societies are active; new initiatives require school approval but starting something new is still possible.",
    teacherGuidanceRating: 4,
    teacherGuidance: "Good. Teachers can recommend debate, Model UN, music, rowing, rugby, basketball and active student societies. STEM teachers are especially useful for students seeking research or competition-based ECL.",
  },
  {
    name: "St. Paul's Convent School (SPCS)",
    type: "Local",
    curricula: ["HKDSE"],
    primaryTarget: "HK / UK",
    students: 4,
    highflyers: 3,
    counsellors: "N/A",
    counsellingEnvironment: "Established Careers and Further Studies support",
    guidanceStarts: "Form 5",
    academicRating: 5,
    academicStrength: "Highly disciplined, achievement-oriented Band 1 girls’ school. Particularly strong in humanities, languages and music alongside excellent HKDSE academics.",
    extracurricularRating: 3,
    extracurricularEnvironment: "Structured and school-directed extracurricular environment with outstanding music, orchestra, choir, drama and community service. Independent ventures are harder to launch, but established programmes—especially music—can provide very high-level achievement opportunities.",
    teacherGuidanceRating: 3,
    teacherGuidance: "Moderate and highly structured. Teachers can guide students toward excellent music, choir, drama and community-service programmes. Independent ventures are more limited, but established arts opportunities are very strong.",
  },
];
